VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 216

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

TILE_SIZE = 16

PLAYER_SPEED = 150

LASER_WIDTH = 8
LASER_HEIGHT = 8
LASER_SPEED = 100

--wall offset
LEFT_WALL = TILE_SIZE
RIGHT_WALL = VIRTUAL_WIDTH - TILE_SIZE - 8
UPPER_WALL = TILE_SIZE * 7
LOWER_WALL = VIRTUAL_HEIGHT - TILE_SIZE